name: nuget-ci-cd
on:
    push:
        branches: [master]
        
jobs:
    build:
        runs-on: windows-latest
        steps: 
            - uses: actions/checkout@v2
            - uses: nuget/setup-nuget@v1
            - uses: actions/setup-dotnet@v1
              with:
                nuget-version: '5.x'
            - run: nuget restore Nuget.sln
            - run: dotnet build /Test/Test.csproj